services:
  - type: web
    name: viber-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: VIBER_AUTH_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: INTERNAL_API_BASE_URL
        value: https://your-internal-api.com
    healthCheckPath: /health
